name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolan/setup-deno@v1

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint --unstable

      - name: Tests
        run: deno test --unstable --allow-ffi
